CHANGELOG.md
deploy/helm/listener-operator/templates/node-daemonset.yaml

Backport of #77
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

Backport to 23.4: Provide automatic migration 23.1 -> 23.4 (#77)

---

CHANGELOG.md
Cargo.lock
rust/operator-binary/Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Upgrade to op-rs 0.45.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml
rust/csi-grpc/Cargo.toml
rust/operator-binary/Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Switch to workspace dependencies

---

docs/modules/listener-operator/pages/listenerclass.adoc

Based on @siegfriedweber's comments in #106.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Refine serviceType docs 

---

CHANGELOG.md
rust/operator-binary/src/listener_controller.rs
tests/templates/kuttl/smoke-nodeport/01-assert.yaml
tests/templates/kuttl/smoke-nodeport/01-create-nginx-statefulset.yaml
tests/templates/kuttl/smoke-nodeport/02-validate-all-ingresses-are-reachable.yaml

Fixes #110
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Make listener selector length more consistent by using uid as name

---

Cargo.lock
Cargo.toml
deploy/helm/listener-operator/crds/crds.yaml
rust/operator-binary/src/main.rs

Better CRD docs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: Better CRD docs

---

docs/modules/listener-operator/pages/reference/crds.adoc
docs/modules/listener-operator/pages/reference/index.adoc
docs/modules/listener-operator/partials/nav.adoc

see title
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat(docs): reference docs

---

Cargo.lock
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Chore: Bumped operator-rs to 0.61

---

deploy/helm/listener-operator/templates/controller-deployment.yaml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add image annotation to controller deployment to fix Tilt

---

CHANGELOG.md
deploy/helm/listener-operator/templates/_helpers.tpl
deploy/helm/listener-operator/templates/node-daemonset.yaml
deploy/helm/listener-operator/templates/roles.yaml
deploy/helm/listener-operator/values.yaml

Part of: https://github.com/stackabletech/issues/issues/501

feat(helm): support labels in values.yaml

---

deploy/helm/listener-operator/values.yaml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add Stackable vendor label to default values.yaml

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
deny.toml

Upgrade dependencies
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Upgrade dependencies

---

docs/modules/listener-operator/pages/index.adoc
docs/modules/listener-operator/pages/installation.adoc
docs/modules/listener-operator/pages/listener.adoc
docs/modules/listener-operator/pages/listenerclass.adoc
docs/modules/listener-operator/pages/security.adoc
docs/modules/listener-operator/pages/volume.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add descriptions

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json

Part of https://github.com/stackabletech/issues/issues/640
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Update to operator-rs 0.76.0

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/listener-operator/Chart.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

release: 24.11.1-rc2

---

.github/workflows/build.yml
CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/listener-operator/Chart.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

release: 24.11.1

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
deploy/helm/listener-operator/templates/roles.yaml
rust/operator-binary/Cargo.toml
rust/operator-binary/src/listener_controller.rs

Part of https://github.com/stackabletech/operator-rs/issues/942
```[tasklist]
```

chore: Update to operator-rs 0.84.0

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json

Reverts the FQDNization-by-default.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Upgrade op-rs to 0.84.1

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/olm-deployer/Cargo.toml
rust/olm-deployer/src/main.rs
rust/operator-binary/Cargo.toml
rust/operator-binary/src/main.rs

Part of https://github.com/stackabletech/issues/issues/639

chore!: Bump stackable-operator to 0.92.0

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/operator-binary/src/csi_server/controller.rs
rust/operator-binary/src/csi_server/node.rs
rust/operator-binary/src/listener_controller.rs
rust/operator-binary/src/main.rs
rust/operator-binary/src/utils/address.rs

Part of https://github.com/stackabletech/issues/issues/642
> [!NOTE]
> `stackable-operator` needs to be released before this can be merged.

chore: Use versioned CRDs

---

CHANGELOG.md
deploy/helm/listener-operator/values.yaml

Part of https://github.com/stackabletech/docker-images/issues/1232
```
--- PASS: kuttl (160.03s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/custom-lbclass_openshift-true_loadbalancer-allocatenodeports-false (8.49s)
--- PASS: kuttl/harness/smoke-nodeport_openshift-true_addressType-Hostname (26.31s)
--- PASS: kuttl/harness/custom-lbclass_openshift-true_loadbalancer-allocatenodeports-true (7.98s)
--- PASS: kuttl/harness/smoke-nodeport_openshift-true_addressType-HostnameConservative (119.64s)
--- PASS: kuttl/harness/smoke-nodeport_openshift-true_addressType-IP (116.81s)
PASS
--- PASS: kuttl (282.05s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/smoke-nodeport_openshift-false_addressType-HostnameConservative (33.39s)
--- PASS: …
```

chore: Bump csi-provisioner version for 25.11.0
